#!/bin/sh

# MeshCentral FreeBSD Service Script

# PROVIDE: meshcentral
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name=meshcentral
desc="MeshCentral"
rcvar=meshcentral_enable

: ${meshcentral_enable:="NO"}
: ${meshcentral_user:="meshcentral"}
: ${meshcentral_group:="meshcentral"}
: ${meshcentral_args:=""}

pidfile=/var/run/${name}/${name}.pid
command="/usr/sbin/daemon"
meshcentral_chdir="/usr/local/meshcentral/node_modules"
command_args="-r -u ${meshcentral_user} -P ${pidfile} /usr/local/bin/node ${meshcentral_chdir}/${name} ${meshcentral_args}"

load_rc_config $name
run_rc_command "$1"
